[build]
  command = "npm run build"
  publish = "build"

[[functions]]
  name = "index"
  path = "index.handler"
  memory = 512
  timeout = 10
  environment = { NODE_ENV = "production" }
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

