[build]
  command = "npm run build"
  publish = "build"

[functions]
  [functions.myFunction]
  name = "myFunction"
  path = "index.js"
  memory = 1024
  timeout = 10
    [functions.myFunction.environment]
    NODE_ENV = "production"

  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/myFunction/:splat"
  status = 200


