[build]
  command = "npm run build"
  publish = "build"

[functions]
  [functions.index]
  name = "index"
  path = "index.handler"
  memory = 1024
  timeout = 10
    [functions.index.environment]
    NODE_ENV = "production"

  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

